### ISSUE TITLE
How can I set requests default timeout?

### ISSUE THREAD

**Issue by wzyonggege** [crflynn/celery-slack#3]
How can I set requests default timeout?

in celery-slack/celery_slack/slack.py

I find:

```
RETRY_AFTER = 0
RATE_LIMITED = False
TIMEOUT = 1
```

**Comment by crflynn** [comment]
You should be able to patch the value using the following:

```python
import celery_slack

celery_slack.slack.TIMEOUT = 10
```

**Comment by wzyonggege** [comment]
@crflynn great! that's what I need

**Comment by crflynn** [comment]
@wzyonggege Hm. That's a good question.

Most of the Slack interactions take place using Celery's [signals](http://docs.celeryproject.org/en/latest/userguide/signals.html), but the task success/failure Slack messages are actually set up by decorating the Task class's `on_success()` and `on_failure() `methods because the signals don't expose all the information needed in the Slack messages.

I see signals for `before_task_publish` and `after_task_publish` but I don't think they would handle this particular issue. I might consider decorating the methods for these actions with a try-except and in the except clause posting the message, but I'll think more about it this week.

In that regard, please open a second issue on the topic and let's move this discussion there.

**Comment by crflynn** [comment]
On the topic of the request timeout, I'll consider adding an option to adjust it in the next release. I'll leave this open until I decide on a solution.

**Comment by wzyonggege** [comment]
great

**Comment by crflynn** [comment]
@wzyonggege: In 0.3.0, you can add an option to override the default timeout:

```python
options = {
    ...
    "slack_request_timeout": 3
    ...
}
```
